//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerasetKararlari.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Veraset
    {
        public int ID { get; set; }
        public string KARARNO { get; set; }
        public string DAVACI { get; set; }
        public string VEFATEDEN { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
