//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerasetKararlari.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kullanicilar
    {
        public int ID { get; set; }
        public string SICIL { get; set; }
        public string ADISOYADI { get; set; }
        public string SIFRE { get; set; }
    }
}
